name: build Home
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    # 构建和部署
    - name: Install and Build
      run: |
        npm ci
        npm run build-storybook
    # 发布
    - name: Deploy  
      uses: JamesIves/github-pages-deploy-action@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: storybook-static